[package]
name = "helium-mnemonic"
edition.workspace = true
authors.workspace = true
license.workspace = true
version = "0.0.1-rc.1"

[dependencies]
bitvec = "*" # inherits from elliptic-curve crate
thiserror = "1"
lazy_static = "1"
sha2 = {workspace = true}

[dev-dependencies]
bs58 = "0"
